when:
  event: [push, manual]
  branch: [main, feature/docker]

steps:
  - name: docker build & push
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: ${CI_REPO_OWNER}/${CI_REPO_NAME}
      tags: [latest]
      dockerfile: Dockerfile
      context: .
      username:
        from_secret: docker_user
      password:
        from_secret: docker_token